### ISSUE TITLE
Add a license to make your code public

### ISSUE THREAD

**Issue by dgerod** [EGiunchiglia/CBTs-Checker#1]
Hi,

I am interested on using and modify your code for my personal research in Robotics, BTs and Learning. Unfortunately I cannot do it because there is not a license assigned to it. Therefore, in case for you it is OK that I other people as me use your code, please, add a license. But, in case that you don't want that let me know.

See: 
* http://opensource.stackexchange.com/q/1720/775
* https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

Thanks in advance.

**Comment by EGiunchiglia** [comment]
Hi! 

The license has been added.

**Comment by dgerod** [comment]
Thanks a lot!
